local players = game:GetService("Players")
local serverStorage = game:GetService("ServerStorage")


game.ReplicatedStorage.EquipVioletValk.OnServerEvent:Connect(function(player)
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("VioletValk") 
	local clone = hat:Clone()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	hi:Destroy()
end)
game.ReplicatedStorage.EquipSparkleValk.OnServerEvent:Connect(function(player)
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("SparkleTime") 
	local clone = hat:Clone()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	hi:Destroy()
end)
game.ReplicatedStorage.EquipEmValk.OnServerEvent:Connect(function(player)
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("EmValk") 
	local clone = hat:Clone()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	hi:Destroy()
	
end)
game.ReplicatedStorage.EquipIceValk.OnServerEvent:Connect(function(player)
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("IceValk")
	local clone = hat:Clone()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	hi:Destroy()
end)
game.ReplicatedStorage.EquipRedValk.OnServerEvent:Connect(function(player)
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("RedValk")
	local clone = hat:Clone()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	hi:Destroy()
end)
game.ReplicatedStorage.EquipBlackValk.OnServerEvent:Connect(function(player)
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("BlackValk")
	local clone = hat:Clone()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	hi:Destroy()
end)
game.ReplicatedStorage.EquipSinisterValk.OnServerEvent:Connect(function(player)
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("SinValk")
	local clone = hat:Clone()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	hi:Destroy()
end)
game.ReplicatedStorage.EquipSummerValk.OnServerEvent:Connect(function(player)
	wait()
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("SummerValk")
	local clone = hat:Clone()
	wait()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	wait()
	hi:Destroy()
end)

game.ReplicatedStorage.EquipDomDead.OnServerEvent:Connect(function(player)
	wait()
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("DeadDom")
	local clone = hat:Clone()
	wait()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	wait()
	hi:Destroy()
end)
game.ReplicatedStorage.EquipDomEmp.OnServerEvent:Connect(function(player)
	wait()
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("DomEmp")
	local clone = hat:Clone()
	wait()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	wait()
	hi:Destroy()
end)
game.ReplicatedStorage.EquipDomPrae.OnServerEvent:Connect(function(player)
	wait()
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("Domprae")
	local clone = hat:Clone()
	wait()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	wait()
	hi:Destroy()
end)
game.ReplicatedStorage.EquipDomGold.OnServerEvent:Connect(function(player)
	wait()
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("Domgold")
	local clone = hat:Clone()
	wait()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	wait()
	hi:Destroy()
end)
game.ReplicatedStorage.EquipRainbowValk.OnServerEvent:Connect(function(player)
	wait()
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("RainbowValk")
	local clone = hat:Clone()
	wait()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	wait()
	hi:Destroy()
end)
game.ReplicatedStorage.EquipGalaxyValk.OnServerEvent:Connect(function(player)
	wait()
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("GalaxyValk")
	local clone = hat:Clone()
	wait()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	wait()
	hi:Destroy()
end)
game.ReplicatedStorage.EquipOrangeValk.OnServerEvent:Connect(function(player)
	wait()
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("OrangeValk")
	local clone = hat:Clone()
	wait()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	wait()
	hi:Destroy()
end)
game.ReplicatedStorage.EquipChunkyyValk.OnServerEvent:Connect(function(player)
	wait()
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("ChunkyyValk")
	local clone = hat:Clone()
	wait()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	wait()
	hi:Destroy()
end)
--sparkles
game.ReplicatedStorage.EquipTealValk.OnServerEvent:Connect(function(player)
	wait()
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("TealValk")
	local clone = hat:Clone()
	wait()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	wait()
	hi:Destroy()
end)

game.ReplicatedStorage.EquipGreenSparkleValk.OnServerEvent:Connect(function(player)
	wait()
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("GreenSparkleValk")
	local clone = hat:Clone()
	wait()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	wait()
	hi:Destroy()
end)

game.ReplicatedStorage.EquipRedSparkleValk.OnServerEvent:Connect(function(player)
	wait()
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("RedSparkleValk")
	local clone = hat:Clone()
	wait()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	wait()
	hi:Destroy()
end)

game.ReplicatedStorage.EquipWhiteSparkleValk.OnServerEvent:Connect(function(player)
	wait()
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("WhiteValk")
	local clone = hat:Clone()
	wait()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	wait()
	hi:Destroy()
	end)
	
game.ReplicatedStorage.EquipPinkSparkleValk.OnServerEvent:Connect(function(player)
		wait()
		print(player.UserId)
		local oof = game.Workspace:WaitForChild(player.Name)
		print(oof)
		local hat = serverStorage:WaitForChild("PinkValk")
		local clone = hat:Clone()
		wait()
		clone.Parent = oof
		local hi = oof:WaitForChild("ValkyrieHelm")
		wait()
		hi:Destroy()
end)

	game.ReplicatedStorage.EquipGoldSparkleValk.OnServerEvent:Connect(function(player)
		wait()
		print(player.UserId)
		local oof = game.Workspace:WaitForChild(player.Name)
		print(oof)
		local hat = serverStorage:WaitForChild("GoldValk")
		local clone = hat:Clone()
		wait()
		clone.Parent = oof
		local hi = oof:WaitForChild("ValkyrieHelm")
		wait()
		hi:Destroy()
end)
game.ReplicatedStorage.EquipMidnightSparkleValk.OnServerEvent:Connect(function(player)
	wait()
	print(player.UserId)
	local oof = game.Workspace:WaitForChild(player.Name)
	print(oof)
	local hat = serverStorage:WaitForChild("DarkBlueSparkle")
	local clone = hat:Clone()
	wait()
	clone.Parent = oof
	local hi = oof:WaitForChild("ValkyrieHelm")
	wait()
	hi:Destroy()
end)




local Players = game:GetService("Players")
local RunService = game:GetService("RunService")


local function onCharacterAdded(character)

	RunService.Stepped:wait()
	local hat = serverStorage:WaitForChild("ValkyrieHelm")
	local clone = hat:Clone()
	character.Head.Transparency = 1
	character.Head.face:Destroy()
	clone.Parent = character	
end

local function onPlayerAdded(player)
	player.CharacterAdded:Connect(onCharacterAdded)
end
Players.PlayerAdded:Connect(onPlayerAdded)

